### ISSUE TITLE
Issue with setting up m3db backups to aws S3

### ISSUE THREAD

**Issue by sid573** [aiven/astacus#64]
I checked the issue myself and the method that is being imported at `astacus/common/m3placement.py` in at [line 15](https://github.com/aiven/astacus/blob/master/astacus/common/m3placement.py#L15) is not present in the specified folder [astacus/proto](https://github.com/aiven/astacus/tree/master/astacus/proto) 

## Error and Warnings
Traceback (most recent call last):
  File "/usr/bin/astacus", line 33, in <module>
    sys.exit(load_entry_point('astacus==0.0.1', 'console_scripts', 'astacus')())
  File "/usr/bin/astacus", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/astacus/main.py", line 9, in <module>
    from astacus import client, server
  File "/usr/local/lib/python3.8/dist-packages/astacus/server.py", line 17, in <module>
    from astacus.coordinator.api import router as coordinator_router
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/api.py", line 6, in <module>
    from .cleanup import CleanupOp
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/cleanup.py", line 12, in <module>
    from astacus.coordinator.coordinator import Coordinator, LockedCoordinatorOp
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/coordinator.py", line 5, in <module>
    from .plugins.base import CoordinatorPlugin, OperationContext, Step, StepFailedError, StepsContext
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/plugins/__init__.py", line 4, in <module>
    from .m3db import M3DBPlugin
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/plugins/m3db.py", line 16, in <module>
    from astacus.common import exceptions, ipc, m3placement
  File "/usr/local/lib/python3.8/dist-packages/astacus/common/m3placement.py", line 15, in <module>
    from astacus.proto import m3_placement_pb2
ImportError: cannot import name 'm3_placement_pb2' from 'astacus.proto' (/usr/local/lib/python3.8/dist-packages/astacus/proto/__init__.py)
root@a6f5c787312f:/# astacus server -c /scripts/astacus-m3-aws.json 
Traceback (most recent call last):
  File "/usr/bin/astacus", line 33, in <module>
    sys.exit(load_entry_point('astacus==0.0.1', 'console_scripts', 'astacus')())
  File "/usr/bin/astacus", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/astacus/main.py", line 9, in <module>
    from astacus import client, server
  File "/usr/local/lib/python3.8/dist-packages/astacus/server.py", line 17, in <module>
    from astacus.coordinator.api import router as coordinator_router
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/api.py", line 6, in <module>
    from .cleanup import CleanupOp
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/cleanup.py", line 12, in <module>
    from astacus.coordinator.coordinator import Coordinator, LockedCoordinatorOp
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/coordinator.py", line 5, in <module>
    from .plugins.base import CoordinatorPlugin, OperationContext, Step, StepFailedError, StepsContext
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/plugins/__init__.py", line 4, in <module>
    from .m3db import M3DBPlugin
  File "/usr/local/lib/python3.8/dist-packages/astacus/coordinator/plugins/m3db.py", line 16, in <module>
    from astacus.common import exceptions, ipc, m3placement
  File "/usr/local/lib/python3.8/dist-packages/astacus/common/m3placement.py", line 15, in <module>
    from astacus.proto import m3_placement_pb2
ImportError: cannot import name 'm3_placement_pb2' from 'astacus.proto' (/usr/local/lib/python3.8/dist-packages/astacus/proto/__init__.py)

It would be very helpful if we can use this.
Thanks

**Comment by fingon** [comment]
It is generated file. There is stuff in the Makefile to generate it (it is default target, e.g. just `make`).

**Comment by fingon** [comment]
PRs to improve the documentation are welcome :)

**Comment by fingon** [comment]
Closing (there's PR to open dev documentation open, but its submitter is not reacting fast so now's your chance too).

**Comment by sid573** [comment]
Hey @fingon thanks for the reply I tried using makefile it worked but I'm facing another issue in the makefile there is `run-server` I used that to check if everything is working fine. Astacus starts with no issue but when I'm trying to call any endpoint `backup`, `list` it shows error.

```
INFO:     Uvicorn running on http://127.0.0.1:5515 (Press CTRL+C to quit)
INFO:     Started reloader process [94] using statreload
INFO:     Started server process [97]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 384, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
    instance = self.app(scope)
TypeError: 'NoneType' object is not callable
INFO:     127.0.0.1:44620 - "POST /backup HTTP/1.1" 500 Internal Server Error

```
I was initially trying with m3db itself but same issue was coming there !!!
Thanks @fingon

**Comment by fingon** [comment]
Good finding, there is something different from what we use in production, I'll investigate it.

**Comment by fingon** [comment]
I think I have something related to this that I already fixed in the `mst-cassandra` branch from last summer, but it never got finished; I think it was a mistake to switch the tests from using the CLI to using somewhat equivalent but not quite route (`python3 -m ..`)

**Comment by fingon** [comment]
Ok, I think the current master works again - please let me know if it breaks. There seems to be some weirdness still with using `astacus` command within container tests, so leaving it out of it for now but I tested manually that this seems to be fine.
